### ISSUE TITLE
Component/sing-up-form refactor: remove unused styles

### ISSUE THREAD

**Issue by vronskyvitaly** [vasilyocheck/flashcards#100]

**Comment by vronskyvitaly** [comment]
![Image](https://github.com/vasilyocheck/flashcards/assets/94834175/c860834a-4c0b-44af-b42b-c67d05041288)



![Image](https://github.com/vasilyocheck/flashcards/assets/94834175/eca93c88-130a-4552-a6b5-1e5f3c6f65b9)

**Comment by vasilyocheck** [comment]
the unused styles are removed
