### ISSUE TITLE
refactor radiogroup: add key and export for props

### ISSUE THREAD

**Issue by vasilyocheck** [vasilyocheck/flashcards#44]

**Comment by vronskyvitaly** [comment]
Please add the ability to export props from the radio component

![Image](https://github.com/vasilyocheck/flashcards/assets/94834175/de5645b7-0fe3-452e-b73d-ae1b84956d3c)

**Comment by vasilyocheck** [comment]
ok, I will do it right now

**Comment by vasilyocheck** [comment]
@vronskyvitaly I have added the export for the radio group props and the key for the component
